import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/navbar";
import { MovixDataProvider } from "./components/context/useMovixData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="luxury">
      <body>
        <MovixDataProvider>
          <Toaster position="bottom-center" />
          <div className="fixed top-12 -translate-x-1/2 left-1/2 right-0 z-50 opacity-95 hover:opacity-100 transition-all">
            <Navbar />
          </div>
          <main className="mt-52 container mx-auto mb-16">
            <section className="flex flex-col space-y-16">
              {children}
            </section>
          </main>
        </MovixDataProvider>
      </body>
    </html>
  );
}
